artipie/http-client

README.md

Part of #1 
Added basic info about project to `README.md`

#1 - Basic info in README.md

---

README.md
src/main/java/com/artipie/http/client/ClientSlices.java
src/main/java/com/artipie/http/client/Settings.java
src/main/java/com/artipie/http/client/package-info.java

Part of #1 
Added basic `ClientSlices` and `Settings` interfaces

#1 - ClientSlices and Settings interfaces

---

pom.xml
src/main/java/com/artipie/http/client/jetty/JettyClientSlice.java
src/main/java/com/artipie/http/client/jetty/package-info.java
src/test/java/com/artipie/http/client/jetty/JettyClientSliceTest.java
src/test/java/com/artipie/http/client/jetty/package-info.java
src/test/resources/log4j.properties

Part of #1 
`JettyClientSlice` added with just request line sending without headers and body

#1 - JettyClientSlice initial

---

src/main/java/com/artipie/http/client/Settings.java
src/test/java/com/artipie/http/client/SettingsTest.java
src/test/java/com/artipie/http/client/package-info.java

Part of #5 
Added default settings class, `Settings.WithProxy` class and simple implementation for `Settings.Proxy`.

#5 - Proxy settings classes

---

src/main/java/com/artipie/http/client/Settings.java
src/test/java/com/artipie/http/client/SettingsTest.java

Part of #14 
Added follow redirects setting

#14 - Added follow redirects setting

---

src/main/java/com/artipie/http/client/Settings.java
src/test/java/com/artipie/http/client/SettingsTest.java

Part of #16 
Added settings for idle timeout

#16 - Added idle timeout setting

---

src/main/java/com/artipie/http/client/Settings.java
src/test/java/com/artipie/http/client/SettingsTest.java

Part of #16 
Added connection timeout settings

#16 - Added connection timeout settings

---

pom.xml

Closes #37 
Set minimal test code coverage to reasonable values

#37 - Set minimal test code coverage to reasonable values

---

pom.xml

#1 - Bumped dependencies

---

src/test/java/com/artipie/http/client/jetty/JettyClientSlicesAndVertxITCase.java

Created IT case with example proxy slice, `JettyClientSlices` and Vertx.

IT case with client slices and vertx

---

src/main/java/com/artipie/http/client/auth/Authenticator.java
src/main/java/com/artipie/http/client/auth/package-info.java
src/test/java/com/artipie/http/client/auth/AuthenticatorBasicTest.java
src/test/java/com/artipie/http/client/auth/package-info.java

Part of #50 
Added `Authenticator` interface along with `Authenticator.Basic` implementation

#50 - Added Authenticator and Authenticator.Basic

---

src/main/java/com/artipie/http/client/PathPrefixSlice.java
src/test/java/com/artipie/http/client/PathPrefixSliceTest.java

Part of #33 
Added `PathPrefixSlice`

#33 - Added PathPrefixSlice

---

src/main/java/com/artipie/http/client/UriClientSlice.java
src/test/java/com/artipie/http/client/UriClientSliceTest.java

Closes #33 
Added `UriClientSlice`

#33 - Added UriClientSlice

---

src/test/java/com/artipie/http/client/HttpServer.java

Closes #67
Fixed stop order in `HttpServer` to prevent possible hang ups

#67 - Fixed stop order in HttpServer to prevent possible hang ups

---

src/main/java/com/artipie/http/client/auth/AuthClientSlice.java
src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java

Part of #50 
`AuthClientSlice` added

#50 - AuthClientSlice added

---

src/main/java/com/artipie/http/client/auth/GenericAuthenticator.java
src/test/java/com/artipie/http/client/auth/GenericAuthenticatorTest.java

Part of #50 
Added `GenericAuthenticator`

#50 - Added GenericAuthenticator

---

pom.xml
src/main/java/com/artipie/http/client/auth/AuthClientSlice.java
src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
src/test/java/com/artipie/http/client/jetty/JettyClientSlicesAndVertxITCase.java

Part of #50 
Fixed issue with `AuthClientSlice` closing response before handled

#50 - Fixed issue with AuthClientSlice closing response before handled

---

src/main/java/com/artipie/http/client/auth/AuthClientSlice.java
src/main/java/com/artipie/http/client/auth/Authenticator.java
src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
src/test/java/com/artipie/http/client/auth/AuthenticatorAnonymousTest.java

Part of #50
Anonymous `Authenticator` and it's support in `AuthClientSlice`

#50 - Anonymous Authenticator and it's support in AuthClientSlice

---

src/main/java/com/artipie/http/client/auth/AuthClientSlice.java
src/main/java/com/artipie/http/client/auth/Authenticator.java
src/main/java/com/artipie/http/client/auth/GenericAuthenticator.java
src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java
src/test/java/com/artipie/http/client/auth/AuthenticatorAnonymousTest.java
src/test/java/com/artipie/http/client/auth/AuthenticatorBasicTest.java
src/test/java/com/artipie/http/client/auth/GenericAuthenticatorTest.java
src/test/java/com/artipie/http/client/jetty/JettyClientSlicesAndVertxITCase.java

Part of #51
`Authenticator` changed to by async

#51 - Authenticator changed to by async

---

README.md

Part of #50 
`AuthClientSlice` and `UriClientSlice` documented

#50 - AuthClientSlice and UriClientSlice documented

---

pom.xml
src/main/java/com/artipie/http/client/auth/OAuthTokenFormat.java
src/main/java/com/artipie/http/client/auth/TokenFormat.java
src/test/java/com/artipie/http/client/auth/OAuthTokenFormatTest.java

Part of #51 
Added `TokenFormat` and `OAuthTokenFormat`

#51 - Added TokenFormat and OAuthTokenFormat

---

src/main/java/com/artipie/http/client/auth/BearerAuthenticator.java
src/test/java/com/artipie/http/client/FakeClientSlices.java
src/test/java/com/artipie/http/client/UriClientSliceTest.java
src/test/java/com/artipie/http/client/auth/BearerAuthenticatorTest.java

Part of #51 
Added `BearerAuthenticator`

#51 - Added BearerAuthenticator

---

src/main/java/com/artipie/http/client/auth/AuthClientSlice.java
src/test/java/com/artipie/http/client/auth/AuthClientSliceTest.java

Closes #66 
Copying request body inside `AuthClientSlice`

#66 - Copying request body inside AuthClientSlice

---

src/main/java/com/artipie/http/client/auth/BearerAuthenticator.java
src/test/java/com/artipie/http/client/auth/BearerAuthenticatorTest.java

Part of #51
Sending params and using auth for token request in `BearerAuthenticator`

#51 - Params and auth for token request in BearerAuthenticator

---

pom.xml

Updated jetty-reactive-httpclient to avoid vulnerability problem with jetty-io

Updated jetty-client

---

src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java

(#21) - Add tests for `trustAll`

---

.pdd
pom.xml
src/test/java/com/artipie/http/client/jetty/JettyClientSliceLeakTest.java
src/test/java/com/artipie/http/client/jetty/JettyClientSlicesAndVertxITCase.java

deps: bump `ppom` from `0.4` to `v1.1.3`

---

README.md

https://github.com/artipie/artipie/issues/1031

chore: clean up README

---

.github/workflows/update-copyright-years.yml

chore: add more extension of files
